name: LLM Python to TypeScript Conversion

on:
  pull_request:
    paths:
      - 'src/models/pydantic_models.py'
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to compare against'
        required: false
        default: 'main'
      target_file:
        description: 'Target Python file to convert'
        required: false
        default: 'src/models/pydantic_models.py'
      output_file:
        description: 'Target TypeScript output path in frontend repo'
        required: false
        default: 'src/types/generated.ts'

jobs:
  convert-models:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    # Checkout frontend repo (where TypeScript will be updated)
    - name: Checkout frontend repo
      uses: actions/checkout@v4
      with:
        repository: yourusername/frontend-repo
        ref: main
        token: ${{ secrets.FRONTEND_REPO_PAT }}
        path: frontend-repo

    # Checkout the PR version of backend repo
    - name: Checkout backend repo (PR version)
      uses: actions/checkout@v4
      with:
        path: backend-pr
        fetch-depth: 0

    # Checkout the base branch version of backend repo
    - name: Checkout backend repo (base version)
      uses: actions/checkout@v4
      with:
        path: backend-base
        ref: ${{ github.event.inputs.base_branch || github.base_ref || 'main' }}
        fetch-depth: 0

    # Get target file paths
    - name: Set file paths
      id: set-paths
      run: |
        echo "TARGET_FILE=${{ github.event.inputs.target_file || 'src/models/pydantic_models.py' }}" >> $GITHUB_ENV
        echo "OUTPUT_FILE=${{ github.event.inputs.output_file || 'src/types/generated.ts' }}" >> $GITHUB_ENV

    # Use the Python to TypeScript action
    - name: Convert Python to TypeScript
      uses: yourusername/pydantic-to-typescript-action@v1
      with:
        base-python-file: backend-base/${{ env.TARGET_FILE }}
        new-python-file: backend-pr/${{ env.TARGET_FILE }}
        current-typescript-file: frontend-repo/${{ env.OUTPUT_FILE }}
        output-typescript-file: frontend-repo/${{ env.OUTPUT_FILE }}
        model-provider: 'anthropic'
        model-name: 'claude-3-haiku-20240307'
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        temperature: '0.1'

    # Create Pull Request in frontend repo
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.FRONTEND_REPO_PAT }}
        path: frontend-repo
        commit-message: "Update TypeScript definitions via LLM"
        title: "LLM-Generated TypeScript Schema Update"
        body: |
          This PR updates the TypeScript schema based on changes in the Python Pydantic models.
          
          Generated by LLM from PR: ${{ github.event.pull_request.html_url || 'Manual trigger' }}
          
          Modified file: `${{ env.OUTPUT_FILE }}`
        labels: 'auto-generated,llm-generated'
        branch: update-ts-schema
        branch-suffix: timestamp
        delete-branch: true