name: Version and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Only trigger on semantic version tags (v1.0.0, v2.3.4, etc.)
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'
      custom_version:
        description: 'Custom version (leave empty to use automatic versioning)'
        required: false
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
        continue-on-error: true  # Temporarily allow tests to fail

      - name: Build
        run: npm run build

      - name: Copy prompt files
        run: |
          mkdir -p dist/prompts
          cp src/*.txt dist/prompts/
          ls -la dist/prompts/

      - name: Check if dist is in .gitignore
        id: check_gitignore
        run: |
          if grep -q "^dist$" .gitignore; then
            echo "dist_ignored=true" >> $GITHUB_OUTPUT
          else
            echo "dist_ignored=false" >> $GITHUB_OUTPUT
          fi

      - name: Update .gitignore for dist if needed
        if: steps.check_gitignore.outputs.dist_ignored == 'true'
        run: |
          sed -i '/^dist$/d' .gitignore
          echo "# Keep dist folder for GitHub Action" >> .gitignore
          echo "# dist/*" >> .gitignore
          echo "# !dist/.gitkeep" >> .gitignore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  verify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      # Print version info for verification
      - name: Print Version Info
        run: |
          echo "Package version: $(node -p "require('./package.json').version")"
          echo "Git commit: $(git rev-parse HEAD)"
          echo "Node version: $(node --version)"

      # Create test files
      - name: Create Test Files
        run: |
          mkdir -p test-files
          
          # Create base Python file
          cat > test-files/base.py << 'EOF'
          from pydantic import BaseModel
          from typing import List, Optional, Dict

          class Address(BaseModel):
              street: str
              city: str
              zipcode: str

          class User(BaseModel):
              id: int
              name: str
              email: str
              addresses: List[Address] = []
          EOF
          
          # Create new Python file with changes
          cat > test-files/new.py << 'EOF'
          from pydantic import BaseModel
          from typing import List, Optional, Dict, Any

          class Address(BaseModel):
              street: str
              city: str
              zipcode: str
              country: Optional[str] = None

          class User(BaseModel):
              id: int
              name: str
              email: str
              addresses: List[Address] = []
              age: Optional[int] = None
              metadata: Dict[str, Any] = {}
          EOF
          
          # Create current TypeScript file
          cat > test-files/current.ts << 'EOF'
          export interface Address {
            street: string;
            city: string;
            zipcode: string;
          }

          export interface User {
            id: number;
            name: string;
            email: string;
            addresses?: Address[];
          }
          EOF
          
          # Create output directory
          mkdir -p test-files/output

      # Execute the action with the built files
      - name: Test Action
        id: test_action
        run: |
          echo "Testing action by executing it directly..."
          # Enable detailed debugging
          NODE_DEBUG=anthropic,langchain,langsmith node dist/index.js
        env:
          INPUT_BASE-PYTHON-FILE: test-files/base.py
          INPUT_NEW-PYTHON-FILE: test-files/new.py
          INPUT_CURRENT-TYPESCRIPT-FILE: test-files/current.ts
          INPUT_OUTPUT-TYPESCRIPT-FILE: test-files/output/updated.ts
          INPUT_MODEL-PROVIDER: ${{ vars.MODEL_PROVIDER || 'anthropic' }}
          INPUT_MODEL-NAME: ${{ vars.MODEL_NAME || 'claude-3-7-sonnet-latest' }}
          INPUT_ANTHROPIC-API-KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          INPUT_OPENAI-API-KEY: ${{ secrets.OPENAI_API_KEY }}
          INPUT_TEMPERATURE: 0.1
          INPUT_VERBOSE: "true"

      # Verify the output looks correct
      - name: Verify Output
        run: |
          echo "Checking if output file was created..."
          if [ ! -f "test-files/output/updated.ts" ]; then
            echo "Error: Output file was not created"
            exit 1
          fi
          
          echo "Verifying output file content..."
          cat test-files/output/updated.ts
          
          # Check for expected content
          if ! grep -q "country?: string" test-files/output/updated.ts; then
            echo "Error: Output file does not contain expected field 'country?: string'"
            exit 1
          fi
          
          if ! grep -q "age?: number" test-files/output/updated.ts; then
            echo "Error: Output file does not contain expected field 'age?: number'"
            exit 1
          fi
          
          if ! grep -q "metadata?: Record<string, any>" test-files/output/updated.ts; then
            echo "Error: Output file does not contain expected field 'metadata?: Record<string, any>'"
            exit 1
          fi
          
          echo "✅ Verification successful: Output contains expected changes"

  version-bump:
    runs-on: ubuntu-latest
    needs: [build, verify]
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.version_type != '' || github.event.inputs.custom_version != '')
    permissions:
      contents: write
      pull-requests: write
    outputs:
      new_version: ${{ steps.get_new_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump version using npm
        if: github.event.inputs.custom_version == ''
        id: npm-version
        run: |
          npm version ${{ github.event.inputs.version_type }} -m "Bump version to %s [skip ci]"
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Set custom version
        if: github.event.inputs.custom_version != ''
        id: custom-version
        run: |
          npm version ${{ github.event.inputs.custom_version }} -m "Set version to %s [skip ci]"
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Get new version
        id: get_new_version
        run: |
          if [ "${{ steps.npm-version.outputs.new_version }}" != "" ]; then
            echo "new_version=v${{ steps.npm-version.outputs.new_version }}" >> $GITHUB_OUTPUT
          else
            echo "new_version=v${{ steps.custom-version.outputs.new_version }}" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        run: |
          git push --follow-tags

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Bump version to ${{ steps.get_new_version.outputs.new_version }}'
          body: |
            Automated version bump to ${{ steps.get_new_version.outputs.new_version }}
            
            This PR was created by the version bump workflow.
          branch: 'version-bump/${{ steps.get_new_version.outputs.new_version }}'
          base: 'main'
          delete-branch: true
          labels: 'version-bump,automated-pr'

  release:
    needs: [build, verify]
    # Only run on version tags or from workflow dispatch that created a new version
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || 
      (github.event_name == 'workflow_dispatch' && needs.version-bump.outputs.new_version != '')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.ref || '' }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Commit and push dist folder
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f dist/
          git commit -m "Build dist for release [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF} || echo "Could not push to ref directly"

      - name: Determine tag name
        id: tag_name
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ needs.version-bump.outputs.new_version }}" >> $GITHUB_OUTPUT
          fi

      - name: Update major version tag
        run: |
          # Get the tag we're using for this release
          RELEASE_TAG="${{ steps.tag_name.outputs.tag }}"
          
          # Extract the major version
          MAJOR_VERSION=$(echo "$RELEASE_TAG" | cut -d. -f1)
          
          # Create or update the major version tag
          git tag -f "$MAJOR_VERSION" "$RELEASE_TAG"
          git push -f origin "$MAJOR_VERSION"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_name.outputs.tag }}
          name: Release ${{ steps.tag_name.outputs.tag }}
          body: |
            ## Python Pydantic to TypeScript LLM Converter ${{ steps.tag_name.outputs.tag }}
            
            This release includes:
            - Compiled action in the `dist` directory
            - Support for both Anthropic Claude and OpenAI models
            - Improved error handling and logging
            
            To use this action, see the examples in the README.
          generate_release_notes: true
          draft: false
          